import { NETTIMOTO_MOPED_MODELS_BY_SUBTYPE } from "@/lib/nettimoto-moped-subtype-models";

// Synkronoitu Nettimoton julkisista merkki- ja mallivalikoista 11.8.2026.
// Yhdistettyä moped-listaa käytetään vain yleisessä haussa. Mopo- ja
// skootterivalintojen tarkat erilliset listat ovat nettimoto-moped-subtype-models.ts:ssa.
// Mukana ovat vain Maskinesissa jo tuetut merkit; Nettimotosta puuttuvien merkkien vanhat listat sailyvat ennallaan.

export type NettimotoVehicleModelGroup =
  | "motorcycle"
  | "snowmobile"
  | "atv"
  | "motocross"
  | "moped";

export const NETTIMOTO_MODELS_BY_VEHICLE = {
  "motorcycle": {
    "Aprilia": [
      "AF1",
      "Atlantic",
      "Caponord",
      "Dorsoduro",
      "ETV",
      "Mana",
      "moto65",
      "MX",
      "Pegaso",
      "RS",
      "RST",
      "RSV",
      "RSV4",
      "RX",
      "RXV",
      "Shiver",
      "SL",
      "SX",
      "Tuareg",
      "Tuono"
    ],
    "Benelli": [
      "49X",
      "502 Cruiser",
      "BKX",
      "BN302",
      "Imperiale",
      "Leoncino",
      "TNT",
      "Tornado",
      "TRE",
      "TRK"
    ],
    "Beta": [
      "ALP",
      "BETA",
      "EVO",
      "Motard",
      "RR",
      "RX",
      "X-Trainer"
    ],
    "BMW": [
      "C",
      "C1",
      "CE 04",
      "F",
      "G",
      "GS",
      "K",
      "LT",
      "M",
      "R",
      "RS",
      "RT",
      "S"
    ],
    "CFMOTO": [
      "125NK",
      "300SR",
      "450CL",
      "450CL-C Bobber",
      "450MT",
      "450NK",
      "450SR",
      "650GT",
      "650MT",
      "650NK",
      "675NK",
      "675SR-R",
      "700 CL-X",
      "700MT",
      "800MT",
      "800MT-X",
      "800NK",
      "1000MT-X",
      "CX-2E",
      "CX-5E",
      "Dual 250"
    ],
    "Ducati": [
      "749",
      "848",
      "998",
      "1098",
      "1198",
      "1199",
      "1299",
      "959 Panigale",
      "Desert X",
      "Diavel",
      "GT",
      "Hypermotard",
      "Monster",
      "Multistrada",
      "Muu malli",
      "Panigale V2",
      "Panigale V4",
      "Scrambler",
      "Sport",
      "SS",
      "ST2",
      "ST3",
      "Streetfighter",
      "Supersport",
      "XDiavel"
    ],
    "Fantic": [
      "Caballero",
      "Casa",
      "Competion",
      "Performance",
      "XE",
      "XEF",
      "XX",
      "XXF"
    ],
    "GasGas": [
      "EC",
      "ES",
      "MC",
      "SM",
      "TXT"
    ],
    "Harley-Davidson": [
      "-",
      "CVO",
      "Dyna",
      "Electra Glide Classic",
      "FXR",
      "Historic",
      "Livewire",
      "Muu",
      "Muu malli",
      "Pan America",
      "Panhead",
      "Road Glide",
      "Shovel",
      "Softail",
      "Sportster",
      "Street",
      "Superlow",
      "Touring",
      "VRSC"
    ],
    "Honda": [
      "C",
      "CA",
      "CB",
      "CBF",
      "CBR",
      "CBX",
      "CL",
      "CM",
      "CMX",
      "CR",
      "CRF",
      "CRM",
      "CTX",
      "CX",
      "Dax",
      "DN-01",
      "Dream",
      "FMX",
      "Forza",
      "FT",
      "GB",
      "GL",
      "Honda WN7",
      "Lead110",
      "MBX",
      "Monkey",
      "MSX",
      "MTX",
      "NC",
      "NS",
      "NSR",
      "NT",
      "NTV",
      "NX",
      "PC 800",
      "PCX",
      "QR",
      "Rebel",
      "Revere",
      "S65",
      "Shadow",
      "Silver Wing",
      "SL",
      "SLR",
      "ST",
      "Super Cub 125",
      "Valkyrie",
      "VF",
      "VFR",
      "VT",
      "VTR",
      "VTX",
      "WN7",
      "X-4",
      "X-ADV",
      "X11",
      "XL",
      "XLV",
      "XR",
      "XRV"
    ],
    "Husqvarna": [
      "701",
      "CR",
      "EE 3",
      "EE 5",
      "FC",
      "FE",
      "FS",
      "Norden",
      "Nuda",
      "SM",
      "SMR",
      "SMS",
      "Svartpilen",
      "TC",
      "TC 65",
      "TE",
      "TR",
      "TX",
      "Vitpilen",
      "WR",
      "WRE"
    ],
    "Indian": [
      "Big Chief",
      "Challenger",
      "Chief",
      "Chieftain",
      "FTR 1200",
      "Muu",
      "Pursuit",
      "Roadmaster",
      "Scout"
    ],
    "Kawasaki": [
      "AR",
      "Eliminator",
      "EN",
      "ER-5",
      "ER-6f",
      "ER-6n",
      "F6",
      "GPX",
      "GPZ",
      "GTR",
      "H1",
      "H2",
      "J300 ABS",
      "KLE",
      "KLR",
      "KLV",
      "KLX",
      "KMX",
      "KS",
      "KX",
      "KZ",
      "LTD",
      "Ninja",
      "s2",
      "Versys",
      "VN",
      "Vulcan",
      "W",
      "Z",
      "Zephyr",
      "ZL",
      "ZN",
      "ZR-7",
      "ZR-7S",
      "ZRX",
      "ZX",
      "ZX-4R",
      "ZX-4RR",
      "ZX-6R",
      "ZX-7R",
      "ZX-9R",
      "ZX-10R",
      "ZX-10RR",
      "ZX-12R",
      "ZXR",
      "ZZ-R",
      "ZZR"
    ],
    "Keeway": [
      "RKF",
      "Superlight"
    ],
    "KTM": [
      "50",
      "65",
      "85",
      "125",
      "150",
      "200",
      "250",
      "300",
      "350",
      "390",
      "400",
      "450",
      "500",
      "505",
      "520",
      "525",
      "530",
      "560",
      "620",
      "625",
      "640",
      "660",
      "690",
      "790",
      "890",
      "950",
      "990",
      "1050",
      "1090",
      "1190",
      "1290",
      "1090 R",
      "1290 Super Adventure R",
      "1290 Super Adventure S",
      "1290 Super Adventure T",
      "1390 Super Adventure R",
      "1390 Super Adventure S",
      "1390 Super Adventure S Evo",
      "1390 Super Duke R",
      "1390 Super Duke R Evo",
      "Freeride",
      "LC4-E",
      "RC",
      "SX-E"
    ],
    "Kymco": [
      "AK",
      "Downtown",
      "Hipster",
      "Like",
      "Quannon",
      "Venox",
      "Xciting",
      "Zing",
      "300i",
      "Agility",
      "Cobra",
      "DJ",
      "Exciting",
      "Grand Dink",
      "Ionex I-One",
      "Movie",
      "People",
      "Super",
      "Super8",
      "ZX"
    ],
    "Moto Guzzi": [
      "750 Nevada Classic",
      "850 Breva",
      "850 T",
      "Breva",
      "California",
      "Griso",
      "Le Mans",
      "Mille Gt",
      "Nevada",
      "Norge",
      "Sport",
      "Stelvio",
      "V7",
      "V9",
      "V11",
      "V35",
      "V65",
      "V85",
      "V100 Mandello"
    ],
    "Royal Enfield": [
      "Bear",
      "Bullet",
      "Classic",
      "Guerrilla",
      "Himalayan",
      "Hunter",
      "Interceptor",
      "Meteor",
      "Scram",
      "Shotgun",
      "Super Meteor"
    ],
    "Suzuki": [
      "A95",
      "DL",
      "DR",
      "DR-Z",
      "GN",
      "GR",
      "GS",
      "GSF",
      "GSR",
      "GSX",
      "GSX-8S",
      "GSX-F",
      "GSX-G",
      "GSX-R",
      "GSX-S",
      "GT",
      "GV",
      "GZ",
      "Intruder",
      "Jr",
      "Katana",
      "LS",
      "M-sarja",
      "pe",
      "RF",
      "RG",
      "RM",
      "RM-Z",
      "SFV 650 Gladius",
      "SP370",
      "SV",
      "T",
      "TL",
      "TS",
      "UK110",
      "V-Strom",
      "VL",
      "VS",
      "VX",
      "VZ",
      "VZR",
      "XF",
      "XN",
      "AN",
      "AY",
      "Estilete",
      "Love"
    ],
    "Triumph": [
      "Adventure",
      "America",
      "Bonneville",
      "Daytona",
      "Legend",
      "Rocket III",
      "Scrambler",
      "Speed",
      "Speed Four",
      "Speedmaster",
      "Speed Triple",
      "Speed Twin",
      "Sprint",
      "Street Triple",
      "Street Twin",
      "TF",
      "Thruxton",
      "Thunderbird",
      "Tiger",
      "Tracker",
      "Trident",
      "Trophy",
      "TT"
    ],
    "Vespa": [
      "Commercial",
      "GTS",
      "ie 250",
      "Piaggio",
      "Primavera",
      "PX",
      "Rally",
      "Vespa",
      "Elettrica",
      "ET2",
      "ET4",
      "Granturismo",
      "GTV",
      "LX",
      "P",
      "PK",
      "S",
      "Sprint"
    ],
    "Yamaha": [
      "Aerox",
      "Beluga",
      "BT",
      "BW",
      "DT",
      "Fazer",
      "FJ",
      "FJR",
      "FS",
      "FZ",
      "FZ1",
      "FZ1-N",
      "FZ1-S",
      "FZ6",
      "FZ6-N",
      "FZ6-S",
      "FZ8-N",
      "FZ8-S",
      "FZR",
      "FZS",
      "FZX",
      "GTS",
      "IT",
      "Jog",
      "Majesty",
      "MT-01",
      "MT-03",
      "MT-07",
      "MT-09",
      "MT-10",
      "MT-125",
      "NIKEN",
      "PW",
      "R3",
      "R6 Race",
      "R9",
      "RD",
      "SR",
      "Street",
      "T-Max",
      "TDM",
      "TDR",
      "Tracer",
      "TT",
      "TT-R",
      "TW",
      "TZR",
      "V-Max",
      "VMX",
      "Warrior",
      "WR",
      "X-City",
      "X-MaX",
      "XJ",
      "XJ6-N",
      "XJR",
      "XS",
      "XSR",
      "XT",
      "XTZ",
      "XV",
      "XVS",
      "XVZ",
      "XZ",
      "YBR",
      "YP",
      "YX",
      "YZ",
      "YZF",
      "YZF-R",
      "YZF-R1",
      "YZF-R3",
      "YZF-R6",
      "YZF-R6R",
      "YZF-R7",
      "YZF-R9",
      "BW´S",
      "Neons",
      "Neos",
      "NMAX",
      "RayZR 125",
      "Slider",
      "Tricity",
      "Versity"
    ],
    "AJP": [
      "PR5",
      "PR7 Adventure"
    ],
    "BSA": [
      "-",
      "Gold Star"
    ],
    "Buell": [
      "1125CR",
      "1125R",
      "Cyclone",
      "Firebolt",
      "Lightning",
      "M2 Cyclone",
      "XB9R Firebolt",
      "XB9SX",
      "XB12",
      "XB12Ss"
    ],
    "Can-Am": [
      "Origin",
      "Outlander",
      "Outlander Max",
      "Pulse",
      "Rally",
      "Ryker",
      "Spyder"
    ],
    "Moto Morini": [
      "A3/344",
      "Corsaro"
    ],
    "MV Agusta": [
      "Brutale",
      "Dragster",
      "F3",
      "F4",
      "F4R",
      "LXP Orioli",
      "Superveloce"
    ],
    "Norton": [
      "-",
      "Atlas",
      "Commando"
    ],
    "Piaggio": [
      "MP3",
      "X9",
      "X10",
      "1",
      "Beverly",
      "Fly",
      "Free",
      "Hexagon",
      "Liberty",
      "NRG",
      "Sfera",
      "Skipper",
      "Typhoon",
      "X8",
      "Xevo",
      "ZIP"
    ],
    "Sherco": [
      "SCF",
      "SE",
      "SE-F",
      "SE-R",
      "SEF-R",
      "SM",
      "ST",
      "ST-R",
      "Trial"
    ],
    "SYM": [
      "Citycom.300i",
      "Allo 50",
      "Fiddle II 50",
      "Jet4 50",
      "Jet4 50 R",
      "Jet 14",
      "Jet BasiX",
      "Jet EuroX 50",
      "Jet SportX 50 S",
      "Jet SportX 50 SR",
      "Mask",
      "Orbit 50",
      "Orbit 125",
      "Orbit II 50",
      "RS 50",
      "Symphony ST 50"
    ],
    "Voge": [
      "300 Rally",
      "DS 625X",
      "DS 800 X Rally",
      "DS 900X"
    ],
    "Zero": [
      "DSR",
      "FX",
      "SR",
      "SR S",
      "X-Line"
    ],
    "TM": [
      "300",
      "Cross",
      "Enduro",
      "MX",
      "SMR"
    ]
  },
  "snowmobile": {
    "Lynx": [
      "20",
      "30",
      "40",
      "250",
      "320",
      "360",
      "520",
      "535",
      "600",
      "5900",
      "6900",
      "49 Ranger",
      "59 Ranger",
      "59 Yeti",
      "69 Ranger",
      "69 Yeti",
      "500 F",
      "3900 Syncro",
      "Adventure",
      "BoonDocker",
      "Brutal RE",
      "Brutal RE 500 MM",
      "Cobra",
      "Commander",
      "Enduro",
      "Explorer",
      "Forest",
      "G-type",
      "GL",
      "GL 3900",
      "Grand-Touring",
      "Mountain",
      "Ranger",
      "Rave",
      "RC600sdi",
      "RE",
      "RS",
      "Safari",
      "Shredder",
      "Sports Touring",
      "Sport Touring",
      "ST",
      "Super",
      "Super Touring",
      "X-trim",
      "Xterrain",
      "Yeti"
    ],
    "Ski-Doo": [
      "Alpine",
      "Backcountry",
      "Citation",
      "Elan",
      "Expedition",
      "Formula",
      "Freeride",
      "Grand Touring",
      "GTX",
      "Legend",
      "Mach 1",
      "Mach Z",
      "Mini Z",
      "Moto-ski Spirit 250",
      "MX Z",
      "Nordik",
      "Renegade",
      "RS",
      "Safari",
      "Skandic",
      "Summit",
      "Touring",
      "Trapper",
      "Tundra"
    ],
    "Polaris": [
      "120 PRO X",
      "340 Touring",
      "440 IQ",
      "500 Classic",
      "500 XC EDGE",
      "500 XC SP",
      "550 Edge Touring",
      "550 LXT",
      "550 sport touring",
      "550 SuperSport",
      "550 Trail Touring",
      "600 Edge Touring",
      "600 edge Variable exhaust system",
      "600 IQ",
      "600 PRO-R",
      "600 PRO X",
      "600 PRO X2",
      "600 R",
      "600 RMK",
      "600 RMK 144",
      "600 Rush",
      "600 SwitchBack",
      "600 XC SP",
      "600RR",
      "650 RMK",
      "700 SwitchBack",
      "700 XC SP",
      "800 PRO X",
      "800 RMK",
      "800 Rush",
      "800 Switchback",
      "800 Touring",
      "800 XC SP",
      "900 Fusion",
      "Axys",
      "Axys SKS",
      "FS Touring",
      "Fusion",
      "Indy",
      "Indy 440",
      "Indy 500",
      "IQ",
      "Nordic Pro",
      "Pro RMK",
      "RMK",
      "Rush",
      "SKS",
      "SwitchBack",
      "Titan",
      "Touring",
      "Trail RMK",
      "Trail Touring",
      "TranSport",
      "Voyageur",
      "WideTrak",
      "WideTrak LX",
      "XC",
      "XCR",
      "XLT"
    ],
    "Arctic Cat": [
      "Bearcat",
      "Blast",
      "Cheetah",
      "Cross Country",
      "Crossfire 6",
      "Crossfire 8",
      "F-sarja",
      "F5",
      "F6",
      "F8",
      "Jag",
      "Jaguar Z1 Sno Pro",
      "M-sarja",
      "Mountain Cat",
      "Pantera",
      "Panther",
      "Powder Special",
      "Riot",
      "Sabercat",
      "Sno Pro Cross country",
      "Sno Pro Snowcross",
      "T-series",
      "TZ1",
      "XF",
      "Z-sarja",
      "ZR",
      "ZR 600 APV",
      "ZR 800 APV"
    ],
    "Yamaha": [
      "Apex",
      "BR250",
      "Enticer",
      "ET",
      "Exciter",
      "FX Nytro",
      "Mountain Max",
      "MP 600 XE Transporter",
      "MultiPurpose",
      "Ovation",
      "Phazer",
      "RS",
      "RS-Viking",
      "RS Rage",
      "RS Vector",
      "RS Venture",
      "RX-1",
      "RX Warrior",
      "Sidewinder",
      "SnoScoot",
      "SR Viper",
      "SRX",
      "SX",
      "SXR",
      "SXVenom",
      "SXViper",
      "Transporter",
      "V-Max",
      "Venture",
      "Viking 540",
      "Viking 540  III",
      "VK"
    ],
    "Taiga": [
      "Nomad"
    ]
  },
  "atv": {
    "Can-Am": [
      "Commander",
      "DS",
      "Maverick",
      "Muu",
      "Outlander",
      "Outlander L",
      "Outlander Max",
      "Rally",
      "renegade",
      "Traxter",
      "XT"
    ],
    "Polaris": [
      "4X4",
      "Ace",
      "Ace 570",
      "ATP",
      "Bigboss 6X6",
      "Diesel",
      "Explorer",
      "General",
      "Hawkeye",
      "Magnum",
      "Outlaw",
      "Phoenix",
      "Polaris",
      "Predator",
      "Ranger",
      "RZR",
      "Scrambler",
      "Sportsman",
      "TELASTOSARJA",
      "Trail Blazer",
      "Trail Boss",
      "XP"
    ],
    "Yamaha": [
      "Blaster",
      "Breeze",
      "Grizzly",
      "Kodiak",
      "Muu",
      "Raptor",
      "Rhino",
      "Viking",
      "Wolverine",
      "YFM",
      "YFZ",
      "YXZ1000R",
      "YZF"
    ],
    "Honda": [
      "90",
      "200",
      "300",
      "350 big 4 x 4",
      "ATC",
      "FA",
      "Foreman",
      "FourTrax",
      "Rincon",
      "TRX"
    ],
    "CFMOTO": [
      "500",
      "C4",
      "C5",
      "CF",
      "CFORCE",
      "Goes",
      "Muu",
      "U10",
      "UFORCE",
      "ZFORCE"
    ],
    "Suzuki": [
      "KingQuad",
      "LT",
      "LT-R",
      "LT-Z",
      "LT80",
      "LTF",
      "Muu",
      "Noppeli",
      "Quad Runner",
      "QuadSport"
    ],
    "Kawasaki": [
      "Brute Force",
      "KFX",
      "KLF",
      "Mule"
    ],
    "Arctic Cat": [
      "450",
      "550",
      "700",
      "400 4x4 Automatic",
      "450 H1 4x4",
      "500 4x4",
      "650 4x4",
      "700 EFI"
    ],
    "TGB": [
      "Avenger",
      "Blade",
      "Hornet",
      "Landmax",
      "Muu",
      "Target"
    ],
    "Kymco": [
      "KXR",
      "MX",
      "MX-er",
      "MXU"
    ],
    "Linhai": [
      "50",
      "420",
      "500",
      "520",
      "550",
      "300 2x4",
      "300 4x4",
      "300 EFI",
      "300 T3B",
      "370 Promax",
      "420 Promax",
      "500 EFI",
      "650L",
      "1100 Diesel EPS UTV",
      "ATV 110",
      "CUV",
      "Landforce",
      "M765",
      "Muu",
      "Promax",
      "T-Boss",
      "T3 400",
      "T3 500"
    ],
    "Segway": [
      "ATS",
      "Fugleman",
      "Snarler",
      "Villain"
    ]
  },
  "moped": {
    "Yamaha": [
      "DT",
      "dt 50cc",
      "PW",
      "TT-R",
      "TZR",
      "Aerox",
      "Beluga",
      "BW´S",
      "Jog",
      "Majesty",
      "Neons",
      "Neos",
      "NMAX",
      "RayZR 125",
      "Slider",
      "T-Max",
      "Tricity",
      "Versity",
      "X-City",
      "X-MaX",
      "YP"
    ],
    "MBK": [
      "Mach",
      "Muu",
      "X-limit",
      "Booster",
      "Nitro",
      "Ovetto",
      "Skyliner",
      "Stunt"
    ],
    "Derbi": [
      "DRD",
      "DRD Evo Limited Edition",
      "GPR",
      "Senda",
      "Sm",
      "X-Race",
      "X-Treme",
      "Atlantis",
      "Boulevard",
      "GP 1",
      "Predator"
    ],
    "Rieju": [
      "E-Bike",
      "MRT",
      "MRX",
      "RR",
      "RRX",
      "Tango",
      "Trophy",
      "Blast Urban"
    ],
    "Aprilia": [
      "Mini RX",
      "MX",
      "RS",
      "RX",
      "SX"
    ],
    "Peugeot": [
      "Looxor",
      "Muu",
      "XP",
      "XPS",
      "Django",
      "Elyseo",
      "Elystar",
      "Elysée",
      "Jet c-Tech",
      "Jet Force",
      "Kisbee",
      "Ludix",
      "Satelis",
      "Speedfight",
      "Speedfight 2",
      "Speedfight 3",
      "Speedfight 4",
      "Squab",
      "Street Zone",
      "SV",
      "TKR",
      "Trekker",
      "Tweet",
      "V-Clic",
      "Vivacity"
    ],
    "Piaggio": [
      "APE",
      "Ciao",
      "Liberty",
      "NRG",
      "Typhoon",
      "1",
      "Beverly",
      "Fly",
      "Free",
      "Hexagon",
      "MP3",
      "Sfera",
      "Skipper",
      "X8",
      "X9",
      "X10",
      "Xevo",
      "ZIP"
    ],
    "Gilera": [
      "Muu",
      "RCR",
      "Runner",
      "Runner 50",
      "SMT",
      "RUNNER SP 50",
      "Stalker"
    ],
    "Beta": [
      "RR",
      "Super Moto"
    ],
    "KTM": [
      "Camping",
      "SX-E"
    ],
    "Honda": [
      "C110",
      "CB 50J",
      "CRF",
      "Monkey",
      "NS",
      "PX",
      "QR",
      "SS",
      "XR"
    ],
    "Suzuki": [
      "Jr",
      "PV",
      "R",
      "R50",
      "RM",
      "S-1",
      "Street Magic",
      "TS",
      "AN",
      "AY",
      "Estilete",
      "Katana",
      "Love",
      "UK110"
    ],
    "Kymco": [
      "Agility",
      "K-Pipe",
      "Super",
      "ZX",
      "300i",
      "Cobra",
      "DJ",
      "Downtown",
      "Exciting",
      "Grand Dink",
      "Ionex I-One",
      "Like",
      "Movie",
      "People",
      "Super8",
      "Xciting"
    ],
    "Keeway": [
      "Cooper",
      "Enduro",
      "Manki",
      "Matrix",
      "Pantera",
      "Pony",
      "TX",
      "X-RAY"
    ],
    "CPI": [
      "GTR",
      "SM",
      "SX",
      "Aragon",
      "Formula",
      "Hussar",
      "Oliver",
      "Popcorn"
    ],
    "Generic": [
      "Trigger",
      "XOR"
    ],
    "Malaguti": [
      "Grizzly",
      "XSM",
      "Crosser",
      "Phantom"
    ],
    "Sherco": [
      "Muu",
      "SE-RS",
      "SM",
      "SM-R",
      "SM-RS",
      "Supermotard"
    ],
    "Tunturi": [
      "Break",
      "City",
      "Hopper",
      "Magnum",
      "Maxi",
      "Mikro",
      "Pappa",
      "Sport",
      "Super Sport",
      "Tiger",
      "Tiger Aqua",
      "trial"
    ],
    "Puch": [
      "MS"
    ],
    "Solifer": [
      "3-SPEED",
      "4-SPEED",
      "Automat",
      "Capri",
      "Export",
      "GT",
      "Pappa",
      "SM",
      "SM MOPO",
      "STM",
      "50R",
      "50S",
      "F1",
      "R8",
      "Retro",
      "SFR",
      "Solana",
      "Star",
      "XTR"
    ]
  },
  "motocross": {
    "KTM": [
      "50",
      "65",
      "85",
      "125",
      "150",
      "200",
      "250",
      "300",
      "350",
      "390",
      "400",
      "450",
      "500",
      "505",
      "520",
      "525",
      "530",
      "560",
      "620",
      "625",
      "640",
      "660",
      "690",
      "790",
      "890",
      "950",
      "990",
      "1050",
      "1090",
      "1190",
      "1290",
      "1090 R",
      "1290 Super Adventure R",
      "1290 Super Adventure S",
      "1290 Super Adventure T",
      "1390 Super Adventure R",
      "1390 Super Adventure S",
      "1390 Super Adventure S Evo",
      "1390 Super Duke R",
      "1390 Super Duke R Evo",
      "Freeride",
      "LC4-E",
      "RC",
      "SX-E"
    ],
    "Yamaha": [
      "Aerox",
      "Beluga",
      "BT",
      "BW",
      "DT",
      "Fazer",
      "FJ",
      "FJR",
      "FS",
      "FZ",
      "FZ1",
      "FZ1-N",
      "FZ1-S",
      "FZ6",
      "FZ6-N",
      "FZ6-S",
      "FZ8-N",
      "FZ8-S",
      "FZR",
      "FZS",
      "FZX",
      "GTS",
      "IT",
      "Jog",
      "Majesty",
      "MT-01",
      "MT-03",
      "MT-07",
      "MT-09",
      "MT-10",
      "MT-125",
      "NIKEN",
      "PW",
      "R3",
      "R6 Race",
      "R9",
      "RD",
      "SR",
      "Street",
      "T-Max",
      "TDM",
      "TDR",
      "Tracer",
      "TT",
      "TT-R",
      "TW",
      "TZR",
      "V-Max",
      "VMX",
      "Warrior",
      "WR",
      "X-City",
      "X-MaX",
      "XJ",
      "XJ6-N",
      "XJR",
      "XS",
      "XSR",
      "XT",
      "XTZ",
      "XV",
      "XVS",
      "XVZ",
      "XZ",
      "YBR",
      "YP",
      "YX",
      "YZ",
      "YZF",
      "YZF-R",
      "YZF-R1",
      "YZF-R3",
      "YZF-R6",
      "YZF-R6R",
      "YZF-R7",
      "YZF-R9",
      "BW´S",
      "Neons",
      "Neos",
      "NMAX",
      "RayZR 125",
      "Slider",
      "Tricity",
      "Versity"
    ],
    "Honda": [
      "C",
      "CA",
      "CB",
      "CBF",
      "CBR",
      "CBX",
      "CL",
      "CM",
      "CMX",
      "CR",
      "CRF",
      "CRM",
      "CTX",
      "CX",
      "Dax",
      "DN-01",
      "Dream",
      "FMX",
      "Forza",
      "FT",
      "GB",
      "GL",
      "Honda WN7",
      "Lead110",
      "MBX",
      "Monkey",
      "MSX",
      "MTX",
      "NC",
      "NS",
      "NSR",
      "NT",
      "NTV",
      "NX",
      "PC 800",
      "PCX",
      "QR",
      "Rebel",
      "Revere",
      "S65",
      "Shadow",
      "Silver Wing",
      "SL",
      "SLR",
      "ST",
      "Super Cub 125",
      "Valkyrie",
      "VF",
      "VFR",
      "VT",
      "VTR",
      "VTX",
      "WN7",
      "X-4",
      "X-ADV",
      "X11",
      "XL",
      "XLV",
      "XR",
      "XRV"
    ],
    "Kawasaki": [
      "AR",
      "Eliminator",
      "EN",
      "ER-5",
      "ER-6f",
      "ER-6n",
      "F6",
      "GPX",
      "GPZ",
      "GTR",
      "H1",
      "H2",
      "J300 ABS",
      "KLE",
      "KLR",
      "KLV",
      "KLX",
      "KMX",
      "KS",
      "KX",
      "KZ",
      "LTD",
      "Ninja",
      "s2",
      "Versys",
      "VN",
      "Vulcan",
      "W",
      "Z",
      "Zephyr",
      "ZL",
      "ZN",
      "ZR-7",
      "ZR-7S",
      "ZRX",
      "ZX",
      "ZX-4R",
      "ZX-4RR",
      "ZX-6R",
      "ZX-7R",
      "ZX-9R",
      "ZX-10R",
      "ZX-10RR",
      "ZX-12R",
      "ZXR",
      "ZZ-R",
      "ZZR"
    ],
    "Husqvarna": [
      "701",
      "CR",
      "EE 3",
      "EE 5",
      "FC",
      "FE",
      "FS",
      "Norden",
      "Nuda",
      "SM",
      "SMR",
      "SMS",
      "Svartpilen",
      "TC",
      "TC 65",
      "TE",
      "TR",
      "TX",
      "Vitpilen",
      "WR",
      "WRE"
    ],
    "Suzuki": [
      "A95",
      "DL",
      "DR",
      "DR-Z",
      "GN",
      "GR",
      "GS",
      "GSF",
      "GSR",
      "GSX",
      "GSX-8S",
      "GSX-F",
      "GSX-G",
      "GSX-R",
      "GSX-S",
      "GT",
      "GV",
      "GZ",
      "Intruder",
      "Jr",
      "Katana",
      "LS",
      "M-sarja",
      "pe",
      "RF",
      "RG",
      "RM",
      "RM-Z",
      "SFV 650 Gladius",
      "SP370",
      "SV",
      "T",
      "TL",
      "TS",
      "UK110",
      "V-Strom",
      "VL",
      "VS",
      "VX",
      "VZ",
      "VZR",
      "XF",
      "XN",
      "AN",
      "AY",
      "Estilete",
      "Love"
    ],
    "GasGas": [
      "EC",
      "ES",
      "MC",
      "SM",
      "TXT"
    ],
    "Beta": [
      "ALP",
      "BETA",
      "EVO",
      "Motard",
      "RR",
      "RX",
      "X-Trainer"
    ],
    "Sherco": [
      "SCF",
      "SE",
      "SE-F",
      "SE-R",
      "SEF-R",
      "SM",
      "ST",
      "ST-R",
      "Trial"
    ],
    "TM": [
      "300",
      "Cross",
      "Enduro",
      "MX",
      "SMR"
    ],
    "Fantic": [
      "Caballero",
      "Casa",
      "Competion",
      "Performance",
      "XE",
      "XEF",
      "XX",
      "XXF"
    ]
  }
} as const satisfies Record<
  NettimotoVehicleModelGroup,
  Record<string, readonly string[]>
>;

export function applyNettimotoVehicleModels(
  target: Record<string, string[]>,
  group: NettimotoVehicleModelGroup
) {
  for (const [brand, models] of Object.entries(NETTIMOTO_MODELS_BY_VEHICLE[group])) {
    target[brand] = [...models];
  }

  if (group === "moped") {
    for (const subtypeModels of Object.values(NETTIMOTO_MOPED_MODELS_BY_SUBTYPE)) {
      for (const [brand, models] of Object.entries(subtypeModels)) {
        const seen = new Set<string>();
        target[brand] = [...(target[brand] ?? []), ...models].filter((model) => {
          const key = model.trim().toLocaleLowerCase("fi");
          if (seen.has(key)) return false;
          seen.add(key);
          return true;
        });
      }
    }
  }

  return target;
}
